### ISSUE TITLE
Getting "command 'extension.zoteroCitationPicker' not found" error

### ISSUE THREAD

**Issue by dbobak** [mblode/vscode-zotero#1]
Zotero 5.0.60, BetterBibTeX 5.1.45, VS Code 1.30.2 installed on Windows 10x64, Polish language version.

After installing the extension I'm getting the "command 'extension.zoteroCitationPicker' not found" error when trying to run the command.

Here is the extensions host log:

`[2019-01-26 23:39:45.031] [exthost] [info] extension host started
[2019-01-26 23:39:45.172] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"activationEvent":"*"}
[2019-01-26 23:39:45.172] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\deni\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\debug-auto-launch\dist\extension
[2019-01-26 23:39:45.181] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2019-01-26 23:39:45.181] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\deni\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\emmet\dist\extension
[2019-01-26 23:39:45.196] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2019-01-26 23:39:45.196] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\deni\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main
[2019-01-26 23:39:45.264] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2019-01-26 23:39:45.264] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\deni\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\merge-conflict\dist\extension
[2019-01-26 23:39:45.272] [exthost] [info] ExtensionService#_doActivateExtension alefragnani.project-manager {"startup":true,"activationEvent":"*"}
[2019-01-26 23:39:45.272] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\deni\.vscode\extensions\alefragnani.project-manager-10.3.0\out\src\extension
[2019-01-26 23:39:45.333] [exthost] [info] ExtensionService#_doActivateExtension ban.spellright {"startup":true,"activationEvent":"*"}
[2019-01-26 23:39:45.334] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\deni\.vscode\extensions\ban.spellright-3.0.22\src\extension
[2019-01-26 23:39:45.797] [exthost] [info] ExtensionService#_doActivateExtension CoenraadS.bracket-pair-colorizer {"startup":true,"activationEvent":"*"}
[2019-01-26 23:39:45.797] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\deni\.vscode\extensions\coenraads.bracket-pair-colorizer-1.0.61\out\src\extension
[2019-01-26 23:39:45.915] [exthost] [info] ExtensionService#_doActivateExtension Equinusocio.vsc-material-theme {"startup":true,"activationEvent":"*"}
[2019-01-26 23:39:45.915] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\deni\.vscode\extensions\equinusocio.vsc-material-theme-2.6.3\extensions\material.theme.config.js
[2019-01-26 23:39:46.012] [exthost] [info] ExtensionService#_doActivateExtension Gruntfuggly.todo-tree {"startup":true,"activationEvent":"*"}
[2019-01-26 23:39:46.013] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\deni\.vscode\extensions\gruntfuggly.todo-tree-0.0.115\extension
[2019-01-26 23:39:47.030] [exthost] [info] ExtensionService#_doActivateExtension ionutvmi.path-autocomplete {"startup":true,"activationEvent":"*"}
[2019-01-26 23:39:47.030] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\deni\.vscode\extensions\ionutvmi.path-autocomplete-1.13.1\out\src\extension
[2019-01-26 23:39:47.055] [exthost] [info] ExtensionService#_doActivateExtension jtanx.ctagsx {"startup":true,"activationEvent":"*"}
[2019-01-26 23:39:47.055] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\deni\.vscode\extensions\jtanx.ctagsx-1.0.9\extension
[2019-01-26 23:39:47.169] [exthost] [info] ExtensionService#_doActivateExtension robertohuertasm.vscode-icons {"startup":true,"activationEvent":"*"}
[2019-01-26 23:39:47.169] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\deni\.vscode\extensions\robertohuertasm.vscode-icons-8.0.0\out\src\
[2019-01-26 23:39:47.318] [exthost] [info] ExtensionService#_doActivateExtension Shan.code-settings-sync {"startup":true,"activationEvent":"*"}
[2019-01-26 23:39:47.318] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\deni\.vscode\extensions\shan.code-settings-sync-3.2.4\out\extension.js
[2019-01-26 23:39:48.133] [exthost] [info] ExtensionService#_doActivateExtension wayou.vscode-todo-highlight {"startup":true,"activationEvent":"*"}
[2019-01-26 23:39:48.133] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\deni\.vscode\extensions\wayou.vscode-todo-highlight-1.0.4\src\extension
[2019-01-26 23:39:48.140] [exthost] [info] ExtensionService#_doActivateExtension GrapeCity.gc-excelviewer {"startup":false,"activationEvent":"onLanguage:plaintext"}
[2019-01-26 23:39:48.140] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\deni\.vscode\extensions\grapecity.gc-excelviewer-2.1.28\out\src\extension
[2019-01-26 23:39:49.122] [exthost] [info] ExtensionService#_doActivateExtension vscode.extension-editing {"startup":false,"activationEvent":"onLanguage:markdown"}
[2019-01-26 23:39:49.122] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\deni\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\extension-editing\dist\extension
[2019-01-26 23:39:49.152] [exthost] [info] ExtensionService#_doActivateExtension vscode.markdown-language-features {"startup":false,"activationEvent":"onLanguage:markdown"}
[2019-01-26 23:39:49.152] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\deni\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\markdown-language-features\dist\extension
[2019-01-26 23:39:49.190] [exthost] [info] ExtensionService#_doActivateExtension DavidAnson.vscode-markdownlint {"startup":false,"activationEvent":"onLanguage:markdown"}
[2019-01-26 23:39:49.190] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\deni\.vscode\extensions\davidanson.vscode-markdownlint-0.23.0\extension
[2019-01-26 23:39:49.682] [exthost] [info] ExtensionService#_doActivateExtension josa.markdown-table-formatter {"startup":false,"activationEvent":"onLanguage:markdown"}
[2019-01-26 23:39:49.683] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\deni\.vscode\extensions\josa.markdown-table-formatter-0.2.3\out\src\extension
[2019-01-26 23:39:49.708] [exthost] [info] ExtensionService#_doActivateExtension mrmlnc.vscode-remark {"startup":false,"activationEvent":"onLanguage:markdown"}
[2019-01-26 23:39:49.708] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\deni\.vscode\extensions\mrmlnc.vscode-remark-1.1.0\out\extension.js
[2019-01-26 23:39:50.322] [exthost] [info] ExtensionService#_doActivateExtension shd101wyy.markdown-preview-enhanced {"startup":false,"activationEvent":"onLanguage:markdown"}
[2019-01-26 23:39:50.323] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\deni\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.3.11\out\src\extension
[2019-01-26 23:39:52.840] [exthost] [info] ExtensionService#_doActivateExtension TomasHubelbauer.vscode-markdown-link-suggestions {"startup":false,"activationEvent":"onLanguage:markdown"}
[2019-01-26 23:39:52.840] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\deni\.vscode\extensions\tomashubelbauer.vscode-markdown-link-suggestions-12.0.3\out\extension
[2019-01-26 23:39:53.396] [exthost] [info] ExtensionService#_doActivateExtension mblode.zotero {"startup":false,"activationEvent":"onCommand:extension.zoteroCitationPicker"}
[2019-01-26 23:39:53.396] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\deni\.vscode\extensions\mblode.zotero-0.1.3\src\extension.js
[2019-01-26 23:39:55.269] [exthost] [info] ExtensionService#_doActivateExtension Ikuyadeu.r {"startup":true,"activationEvent":"workspaceContainsTimeout:*.r|.rd|.rmd"}
[2019-01-26 23:39:55.269] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\deni\.vscode\extensions\ikuyadeu.r-1.0.2\out\src\extension
[2019-01-26 23:40:03.768] [exthost] [info] eager extensions activated
`

**Comment by mblode** [comment]
Thank you for letting me know! I've just pushed an update that should fix this issue. Just an issue with the "request" package that is now required. Please let me know if you have other problems.

**Comment by dbobak** [comment]
I'm sorry to say that, but the problem still exists. I've completely removed the extension and installed new version (1.4). The error is the same.

**Comment by mblode** [comment]
@dbobak Agh my bad! Try again with the newest version (which I accidentally forgot to publish): **0.1.7**

I'll definitely be more rigorous next time... I just got confused with my local .visx package that I was using for debugging purposes.
